### ISSUE TITLE
Alert conflicting with Bootstrap alert

### ISSUE THREAD

**Issue by caroso1222** [caroso1222/notyf#1]
When an alert is created, a classname `notyf alert` is assigned to the element. The class `alert` is a special class in Bootstrap so it's setting an additional padding making the card look pretty big.

Fix this by either changing the class name or manually setting `padding:0` to the `alert` element.

**Comment by milosdjakonovic** [comment]
Nice lib!
About this issue, can it be solved by changing `card.className` to `Notyf_alert` (for example) [here](https://github.com/caroso1222/notyf/blob/master/src/notyf.js#L36) and in scss source?

As the matter of fact, all notyf's css class names may be prefixed this way ( `Notyf_` ), to avoid conflicts.

**Comment by caroso1222** [comment]
You're right man thank you for suggesting that. Been away these holidays, but now I'm back to it. Gonna fix that in no time. I think I'm going to follow [BEM methodology](https://en.bem.info/methodology/css/) for consistency.

**Comment by caroso1222** [comment]
Resolved in https://github.com/caroso1222/notyf/commit/45e327273fb8d3524f15ab56f75dcb36d35d489a by using BEM methodology for CSS classes.
