### ISSUE TITLE
large monitor css issue

### ISSUE THREAD

**Issue by scttcper** [caroso1222/notyf#12]
![kapture 2017-05-01 at 21 11 27](https://cloud.githubusercontent.com/assets/1400464/25603707/cf8592b2-2eb2-11e7-80de-9a13e59e1740.gif)

I'm emulating a wide monitor here with dev tools, but it also didn't display correctly on my ultrawide windows setup. Its not reaching the side and then on the .disappear it stretches. Hope that makes sense, cool library!

**Comment by caroso1222** [comment]
Thanks for reporting this issue. I'll take a look at the PR and get this fixed this asap.

**Comment by caroso1222** [comment]
Fixed in v3.0.0.
