### ISSUE TITLE
Website SSL certificate expired

### ISSUE THREAD

**Issue by TixieSalander** [caroso1222/notyf#122]
Hi!
The Notyf SSL certificate is expired since Februrary 7th. 

![Screenshot 2022-02-28 at 10 40 13](https://user-images.githubusercontent.com/2143796/155960567-00429d21-1ccd-4e66-8058-82a73b024d6f.png)

I hope it's just an oversight and that everything is going OK for you ❤️

**Comment by KrunchMuffin** [comment]
site is just dead now.

**Comment by caroso1222** [comment]
yeah sorry, I was out for a while. I moved to gh pages now; apex domain won't work, but at least www does now

www.carlosroso.com/notyf

sorry for the inconveniences
