### ISSUE TITLE
I wanna dismiss button and click action

### ISSUE THREAD

**Issue by otaroo** [caroso1222/notyf#13]
Can you tell me how to add  dismiss button and click action?

**Comment by McFcologne** [comment]
You can create a button or a anchor whith the suitable code and append it as another child to the wrapper... But this is somehow against the minimalistic approach.

**Comment by fibigerg** [comment]
+1 for this feature! Nice minimalistic cross in the right side of the message would boost UX a lot.

**Comment by caroso1222** [comment]
Hey guys. Sorry for being silent these last months. I like the idea of adding the close button at the top right of the Notyf. I'll work on this and add it to v3.x.

**Comment by caroso1222** [comment]
v3.0.0 has been released with a lot of cool things. I left this for 3.1.0 as I didn't really got time to add this feature, but it's on the roadmap for sure.

**Comment by caroso1222** [comment]
Closing as resolved in https://github.com/caroso1222/notyf/pull/51. This feature is now available in v3.3.0.
