### ISSUE TITLE
Small screen style fix doesn't work

### ISSUE THREAD

**Issue by alexandermendes** [caroso1222/notyf#15]
Probably because there is no `.notyf__container`!

https://github.com/caroso1222/notyf/blob/45e327273fb8d3524f15ab56f75dcb36d35d489a/src/notyf.scss#L186-L195

**Comment by jgentes** [comment]
+1

**Comment by jgentes** [comment]
FYI I was able to simply use .notyf and it did the trick:
```
// notyf notifications fix for small screens
@media only screen and (max-width: 736px){
  .notyf {
    width: 90%;
    margin: 0 auto;
    display: block;
    right: 0;
    left: 0;
  }
}
```

**Comment by ayushsharma82** [comment]
Change notyf__container to notyf to apply Fix. It works perfectly.

**Comment by alexandermendes** [comment]
Sure yeah, was just a note to fix it in the actual code, closing as a PR probably wouldn't be merged anyway (seems a bit quiet).
