### ISSUE TITLE
unsafe HTML?

### ISSUE THREAD

**Issue by jgentes** [caroso1222/notyf#17]
Curious to know if there's a way to allow notyf.alert(message_with_html) to be displayed properly?

@caroso1222 Your module allowed us to finally toss jQuery from our entire app.. so thanks!!

**Comment by caroso1222** [comment]
Hey @jgentes sorry for being so silent these last months. I'm so glad to hear you found value in the module. I'll work on adding support for messages with html and add it to v3.x.

**Comment by caroso1222** [comment]
As promised, v3.0.0 now supports toasts with HTML content. Thanks for the idea.

Marking this as resolved.
