### ISSUE TITLE
Sorry for being such an irresponsible maintainer

### ISSUE THREAD

**Issue by caroso1222** [caroso1222/notyf#21]
I know there are quite several folks out there using this package and I've been such an irresponsible maintainer to abandon my dear Notyf. This was my first open source package and I've been through a lot these last 2 years.

I'm happy to take the lead on the project again, resolve the issues, close/merge the PRs and set a roadmap for Notyf 3.0 with better animations, more features, better API and more.

Sorry again to all of you who have opened issues or PRs that I have simply ignore or overlooked :(.

**Comment by rijkvanzanten** [comment]
Hey @caroso1222!

Hopefully you're doing well 🙂

Do you have any information on the roadmap / _better API_?

**Comment by caroso1222** [comment]
Hey @rijkvanzanten, thanks for asking. I don't have a roadmap, can't really abide to a deadline. I've made good progress in v3.0 though. You can see that in the 3.0.0 branch. I've basically made the codebase a lot more maintainable, so most of the stuff is just internals refactoring. I'll post the updates in this thread from now on.

**Comment by axZerk** [comment]
I will try to help fix some minor bugs in version 2 and contribute to 3.0 release.

**Comment by caroso1222** [comment]
I finally released v3.0.0! It's looking rad. Thanks for the patience and sorry for taking too long! 🙏
