### ISSUE TITLE
Custom notification types

### ISSUE THREAD

**Issue by snipervld** [caroso1222/notyf#23]
Hi, thanks for such a great library.

For now, there are only two types of notification: `alert` and `confirm` with `notyf--alert` and `notyf--confirm` css classes respectively.
It would be better, if there was a way to add another type of notification or css class. For example, type `warning` (with another class).

Example API:
```
const notyf = new Notyf();

notyf.custom('We had some trouble', { className : 'warning' });
```

Or based on issue #22:

```
const notyf = new Notyf({
  types: {
    warning: {
      delay: 1000, // #7
      duration: 2000, // #6
      icon: 'fa-foo-fi-fu',
      notificationClass: 'notyf--warning',
    },
  },
});

const errorNotification = notyf.custom({
  type: 'warning'
  title: 'Some uncritical issue',
  message: 'We had some trouble',
});
```

**Comment by caroso1222** [comment]
Thanks for this idea! v3.0.0 has been released with full support for registering new types as requested. Here's how to do it:

```javascript
const notyf = new Notyf({
  types: [
    {
      type: 'info',
      backgroundColor: 'blue',
      icon: false
    }
  ]
})

notyf.open({ type: 'info', message: 'Do not forget to pause the timer' });
```
