### ISSUE TITLE
Automatic width + Bootstrap adaptation (box-sizing)

### ISSUE THREAD

**Issue by alexz006** [caroso1222/notyf#28]
Hi, maybe someone will like it https://jsfiddle.net/9tehLvpx/

**Comment by caroso1222** [comment]
Thanks for this. I took this suggestion to fix the rendering in v3.0.0. Width is adapted to its content now:

![2019-03-19 20 40 13](https://user-images.githubusercontent.com/3689856/54653078-52b2ca00-4a87-11e9-973a-8b89db5f9057.gif)
