### ISSUE TITLE
Problem with styling in a specific viewport range

### ISSUE THREAD

**Issue by axZerk** [caroso1222/notyf#30]
Took the new version for a spin and here is what happened - at some point ripple effect styling gets weird. Please see very short screen recording below that has all the required info.

PS: with `ripple: false` styling is fine

[Screen recording](https://monosnap.com/file/sjtqYoT5DsV0wLU1o3SjfGFY9pt5Bb)

**Comment by caroso1222** [comment]
Good catch Alex. I'll need to work on the full range of viewport width. I added the ability to disable the ripple precisely for this, I knew the ripple was going to fail at some unexpected point.

I'll work on the fix and release asap, thanks!
