### ISSUE TITLE
Styles are broken in case of long message

### ISSUE THREAD

**Issue by okucheruk** [caroso1222/notyf#38]
Hi Carlos.
Toasts style are broken in case of long message.

![Screen Shot 2019-10-01 at 5 31 18 PM](https://user-images.githubusercontent.com/50623030/65971799-73fe6500-e471-11e9-8d28-1c45ace83d9d.png)

Repro steps:
```
const message = `
Unless required by applicable law or agreed to in writing, software distributed under the License
Unless required by applicable law or agreed to in writing, software distributed under the License
Unless required by applicable law or agreed to in writing, software distributed under the License
Unless required by applicable law or agreed to in writing, software distributed under the License
Unless required by applicable law or agreed to in writing, software distributed under the License
Unless required by applicable law or agreed to in writing, software distributed under the License
Unless required by applicable law or agreed to in writing, software distributed under the License

new Notyf().error({
  message: message,
  duration: 20000,
});
`

macOS
Safari Version 12.1 (14607.1.40.1.3)
Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by okucheruk** [comment]
Issue related to `notyf__ripple` css class.

Workaround: `ripple: false`

**Comment by caroso1222** [comment]
Good catch. So, does it work fine when you disable the ripple?

**Comment by okucheruk** [comment]
Yep

![Screen Shot 2019-10-02 at 12 05 07 AM](https://user-images.githubusercontent.com/50623030/66000551-54cefa00-e4a8-11e9-9450-75124ceb8c76.png)

**Comment by caroso1222** [comment]
Nice! I'll close this issue then. Ripple is only there for short standard messages. Disabling it for some longer messages is the intended solution. Thanks for reporting it!
