### ISSUE TITLE
Positioning of the toast, how?

### ISSUE THREAD

**Issue by resuta566** [caroso1222/notyf#43]
How would I change the position of the toast? Will it be included in the future release? I am using Angular 8.2.11. Thanks :)

**Comment by caroso1222** [comment]
Yeah, duplicate of https://github.com/caroso1222/notyf/issues/36. I'll work on this for the next release.

**Comment by resuta566** [comment]
> Yeah, duplicate of #36. I'll work on this for the next release.

Oops, sorry I didn't see that. btw thanks, this is very beautiful :+1:

**Comment by prince272** [comment]
Please what's the center postilion css

**Comment by Jesspu** [comment]
If you want to move it to the left side, I did this in my css.

.notyf {
  right: auto !important;
  left: 30px !important;
}

Guessing at some point it will be supported, but this works for now.

**Comment by caroso1222** [comment]
Closing. This feature has been introduced in https://github.com/caroso1222/notyf/pull/48 and is available in `3.2.0`.

Thanks for the report and the follow-up!
