### ISSUE TITLE
Internet explorer compatibility broken

### ISSUE THREAD

**Issue by mdix** [caroso1222/notyf#44]
Using `findIndex` w/o polyfilling breaks notyf in all available Internet Explorers.

Usage:
https://github.com/caroso1222/notyf/blob/694728ea786b4b391dac17ad60616d8b4b121076/src/notyf.ts#L73

Error in Internet Explorer:
![Screenshot 2019-12-11 at 13 02 18](https://user-images.githubusercontent.com/1155015/70620603-01032e80-1c18-11ea-87bf-d622156bb1c8.png)

**Comment by caroso1222** [comment]
Good catch, thanks for opening the issue. I didn't really have any plans of supporting IE (unpopular opinion, I know) but if this is the only pain point to make it work in IE then I'll look into it and fix it in the next patch. Thanks again for noting it!

**Comment by mdix** [comment]
Thanks. I'm glad to hear that and yes, it is the only thing that prevents notyf from working in IE11. After I polyfilled `Array.prototype.findIndex` everything worked as expected.

**Comment by mdix** [comment]
You can just put [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex#Polyfill) in a file and use it, I guess.

**Comment by terales** [comment]
@caroso1222 would you accept a PR on this?

I'll just implement the old way of finding an index instead of a modern "findIndex" method to make it usable without any polyfills.

**Comment by caroso1222** [comment]
Hey @terales. Sorry for the late reply, still coming back from holidays. Yeah definitely, thanks! Take a stab at it and I'll review the PR.

**Comment by terales** [comment]
@mdix can you prepare a PR, please?

I'm on Ubuntu since January and it seems that I would be without available Windows machine for a while now.

**Comment by caroso1222** [comment]
Fixed it already. Thank you all for the help! 😃
