### ISSUE TITLE
Notification delay

### ISSUE THREAD

**Issue by ConsoleTVs** [caroso1222/notyf#6]
hello! The delay option should be renamed to duration in my opinion, and a new simple "delay" should be added to prevent overlapping, for example; if you add 3 notifications at the same time (alert for example) they all appear and dissapear at the same time, when in fact, setting up a diferent duration or delay to dissapear to each one, should fix it.

It can be done creating multiple instances in your example; but that is not how it should be because if i have 10 alerts, i must have 10 different instances to avoid overlapping!

**Comment by caroso1222** [comment]
Hey! sorry for being so unresponsive in the last year. I'm taking over the project again. 

I like the idea of having some way of adding delay between consecutive notifications without having to create new instances. I'll improve the API for 3.x and will take this feature into account.

Thanks again for bringing that up!

**Comment by ConsoleTVs** [comment]
Great to hear that!

**Comment by caroso1222** [comment]
v3.0.0 has been released and 'delay' has been renamed to 'duration', as suggested. Thanks for the idea!

**Comment by ConsoleTVs** [comment]
You're welcome!

**Comment by PeterHuefner** [comment]
Is there any possibility to handle multiple notifications? In my tests they overlap themselves.
It would be nice when they position automatically as a list. As the toastr lib does (but it depends on jquery, that's why I come up to your cool lib).
