### ISSUE TITLE
CDN version

### ISSUE THREAD

**Issue by 64J0** [caroso1222/notyf#64]
Please, add a CDN link version, so we can use this package with only vanilla js.

**Comment by caroso1222** [comment]
Hadn't thought about that. I will definitely do it. 

I have never done so, do you have any recommendations? I mean, something that will also allow to manage and publish versions appropriately?

Thanks for the suggestion!

**Comment by 64J0** [comment]
I have never done this too, but this guy made: https://github.com/apvarun/toastify-js. He made a feature like yours too.

**Comment by caroso1222** [comment]
I think it's a great idea so I'll leave this one open.

**Comment by caroso1222** [comment]
I just realized notyf is already getting 93k hits a month on jsdelivr! I updated the docs with the link to jsdelivr. Thanks again!

```html
<html>
  <head>
    ...
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.css">
  </head>
  <body>
    ...
    <script src="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.js"></script>
  </body>
</html>
```
