### ISSUE TITLE
Extensions: warn & separate delay values

### ISSUE THREAD

**Issue by mmokross** [caroso1222/notyf#7]
Hello,

I hope it is ok for you, that I forked your repository and made some extensions:
* enable warn notifications
* separate delay values

I'm not sure, if you can merge these extensions back into your repository.

If you like, you find it at: https://github.com/wolfheart/notyf-extended

Thank you for your original notyf.
Michael

**Comment by caroso1222** [comment]
@wolfheart Wow this is so goood! Thank you for that! Would you like to create a PR for this? or is it good for you that I take from your code and complement Notyf to release a new version (with respective credits, obviously)?

Thanks again, good job!

**Comment by caroso1222** [comment]
v3.0.0 has been released with support for these features. Thanks for the idea!

**Comment by mmokross** [comment]
Cool! 👍  Sorry, I forgot to answer to your request!
