### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by zwjohn** [caroso1222/notyf#73]
This is a great library and I use it on my site, however, it would be nice to change the configuration dynamically. For example, after a Notyf object is created with dismiss disabled, I want to enable dismiss feature on the fly base on some conditions, or change duration. This is currently not possible. It would be nice to be able to configure these configurations.

Thanks for your works

**Comment by caroso1222** [comment]
I see. I think you can solve this in 2 ways:

1. All the global properties can be overridden for individual notifications.

```javascript
const notyf = new Notyf({ dismissible: false, duration: 1000 }); // global config
notyf.success('I am a fast notification');

// now you want it to render with different configurations
notyf.success({
  message: 'I am a slow notification',
  duration: 8000,
  dismissible: true
});
```

2. You can make use of the public property `options` in your Notyf instance to create a new instance
```javascript
let notyf = new Notyf({ dismissible: false, duration: 1000 }); // global config
notyf.success('I am a fast notification');

// now I want notifications to be dismissible
notyf = new Notyf({
  ...notyf.options,
  dismissible: true
});
notyf.success('I can be dismissed');
```

Let me know if you can work it out this way.

**Comment by zwjohn** [comment]
Base on my understanding, I am afraid both would not work, as I have form control with states maintained in the first notification, both of your solutions will cause re-rendering of the notification, hence the state will be lost. Thanks!

**Comment by caroso1222** [comment]
Oh! I see. So you need the notification to change in "real-time", not just re-render the notification.

I agree that's a cool feature, but it's unfortunately not in the scope of what I envision Notyf to support, at least in the near future. It's meant to be a middle ground between a basic and a complex toaster, and I think this feature fits into the advanced type.

Thanks for opening the issue! I'll close it for now but I'm happy to reopen if it gets attention later again.
