### ISSUE TITLE
Will a UMD be released with the library?

### ISSUE THREAD

**Issue by jps1st** [caroso1222/notyf#78]
Hi. Thanks for building this great lib. It's an integral part of one of our libs so we'd love to have a UMD for it since it'll be used in multiple projects that come together at runtime. We're using webpack externals for the libs that are commonly used and I guess other people would do so for sure.

Will a UMD file be released with the library? Again thanks for the work.

**Comment by Strajk** [comment]
+1 

I would like to use this lib in Chrome extension without a build step. Chrome Web Store disallows minified code, so I cannot really use `notyf.min.js`

**Comment by caroso1222** [comment]
Thanks @Strajk! The UMD is already available in version 3.9.0.

**Comment by Strajk** [comment]
@caroso1222 awesome, thanks!

I still consider myself new to open source world and so far I have only the best experience :) 

https://www.youtube.com/watch?v=StTqXEQ2l-Y
