### ISSUE TITLE
Renew SSL certificate of the demo site

### ISSUE THREAD

**Issue by josuemontano** [caroso1222/notyf#86]
The SSL certificate of the demo site expired a few days ago.

<img width="592" alt="Screen Shot 2020-08-30 at 9 09 12 AM" src="https://user-images.githubusercontent.com/1854377/91659866-86798800-eaa0-11ea-92b6-4851c255a0d3.png">

**Comment by caroso1222** [comment]
Thanks for noting it. I was moving countries and couldn't find time for this. It's fixed already.
